# Generated by Django 4.2.7 on 2023-11-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
