# Generated by Django 4.2.7 on 2023-11-26 05:59

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ресторана')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес ресторана')),
                ('contact_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Контактный номер')),
                ('avg_check', models.DecimalField()),
                ('description', models.TextField(verbose_name='Описание')),
                ('restaurant_image', models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.image_profile_path, verbose_name='Фотография профиля ресторана')),
                ('photo_1', models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.image_restaurant_path, verbose_name='Первая фотография ресторана')),
                ('photo_2', models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.image_restaurant_path, verbose_name='Вторая фотография ресторана')),
                ('photo_3', models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.image_restaurant_path, verbose_name='Третья фотография ресторана')),
                ('status', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.district')),
                ('features', models.ManyToManyField(to='restaurants.feature')),
                ('kitchens', models.ManyToManyField(to='restaurants.kitchen')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='VisitPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_opening_time', models.TimeField()),
                ('monday_closing_time', models.TimeField()),
                ('tuesday_opening_time', models.TimeField()),
                ('tuesday_closing_time', models.TimeField()),
                ('wednesday_opening_time', models.TimeField()),
                ('wednesday_closing_time', models.TimeField()),
                ('thursday_opening_time', models.TimeField()),
                ('thursday_closing_time', models.TimeField()),
                ('friday_opening_time', models.TimeField()),
                ('friday_closing_time', models.TimeField()),
                ('saturday_opening_time', models.TimeField()),
                ('saturday_closing_time', models.TimeField()),
                ('sunday_opening_time', models.TimeField()),
                ('sunday_closing_time', models.TimeField()),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работ',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.type'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='visit_purposes',
            field=models.ManyToManyField(to='restaurants.visitpurpose'),
        ),
    ]
