# Generated by Django 4.2.7 on 2023-11-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_avg_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_average_check',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_average_check',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
