# Generated by Django 4.2.7 on 2024-04-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_table_is_available_reservation_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
    ]
