# Generated by Django 4.2.7 on 2024-04-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_table_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='max_average_check',
            field=models.PositiveIntegerField(verbose_name='Максимальный средний чек'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='min_average_check',
            field=models.PositiveIntegerField(verbose_name='Минимальный средний чек'),
        ),
    ]
