# Generated by Django 4.2.7 on 2024-04-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_max_average_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Контактный номер'),
        ),
    ]
