# Generated by Django 4.2.7 on 2024-04-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurant_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAdditionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Map_photo/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Заявка на редактирование карты',
                'verbose_name_plural': 'Заявки на редактирование карты',
            },
        ),
        migrations.CreateModel(
            name='TableAdditionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('photo', models.ImageField(upload_to='table_photos/')),
                ('map_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablerequests', to='restaurants.mapadditionrequest')),
            ],
            options={
                'verbose_name': 'Стол для редактирование карты',
                'verbose_name_plural': 'Столы для редактирование карты',
            },
        ),
    ]
